#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely
# Displays "I am invincible!!!" when receiving a SIGTERM signal

# Trap SIGTERM signal and display the invincibility message
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
