#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely
# When receiving SIGTERM, displays "I am invincible!!!" and continues

# Trap SIGTERM signal and display message
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
